name: Run tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    test-php:
        name: Test on php ${{ matrix.php-version }} and ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        runs-on: ${{ matrix.os }}
        continue-on-error: ${{ matrix.experimental }}
        strategy:
            matrix:
                php-version: ["5.5", "5.6", "7.1", "7.2", "7.3", "7.4", "8.0"]
                experimental: [false]
                os: [ubuntu-latest]
                composer-options: ['']
                include:
                    - { php-version: '8.1', composer-options: '--ignore-platform-req=php', experimental: true, os: ubuntu-latest }
        steps:
            - uses: actions/checkout@v2
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  coverage: xdebug
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install --no-interaction --prefer-dist --no-progress ${{ matrix.composer-options }}
            - name: Run php tests
              run: composer run test
            - name: Send coverage
              uses: codecov/codecov-action@v1
